# -*- coding: utf-8 -*-
"""Крехова 26.04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z49abRAJhLmE4dY5V6Db7x08BO8tERVt
"""

install.packages("dplyr")
library(dplyr)
library(tidyverse)
install.packages('nortest')
library(nortest)
install.packages("tseries")
library(tseries)
install.packages("car")
library(car)

a <- read.csv2('/content/datas1.csv')
head(a, 5)

cols_to_clean <- c("AvgPitStopTime", "Laps", "TotalPitStops")


outlier_indices <- c()

for (col in cols_to_clean) {
  Q1 <- quantile(a[[col]], 0.25, na.rm = TRUE)
  Q3 <- quantile(a[[col]], 0.75, na.rm = TRUE)
  IQR <- Q3 - Q1

  lower <- Q1 - 1.5 * IQR
  upper <- Q3 + 1.5 * IQR

  outliers <- which(a[[col]] < lower | a[[col]] > upper)


  outlier_indices <- union(outlier_indices, outliers)
}


clean <- a[-outlier_indices, ]

install.packages("nortest")
install.packages("tseries")

library(nortest)
library(tseries)

cols_to_test <- c("AvgPitStopTime", "Laps", "TotalPitStops")

for (col in cols_to_test) {
  cat("===== Нормальность для:", col, "=====\n")

  cat("Shapiro-Wilk:\n")
  print(shapiro.test(clean[[col]]))

  cat("\n--------------------------\n\n")
}

"""Данные в этом датасете распределены ненормально"""

library(car)

clean$Constructor <- as.factor(clean$Constructor)
leveneTest(AvgPitStopTime ~ Constructor, data = clean)

"""# **1. t.test**

---

# Непарный t-test
"""

group1 <- clean$AvgPitStopTime[clean$Constructor == "McLaren"]
group2 <- clean$AvgPitStopTime[clean$Constructor == "Red Bull"]

t.test(group1, group2, var.equal = TRUE)

"""# Парный t-test"""

verstappen_data <- clean[clean$Driver == "Max Verstappen" & clean$Season %in% c(2022, 2019), ]

verstappen_data <- verstappen_data[order(verstappen_data$Round, verstappen_data$Season), ]

verstappen_2022 <- verstappen_data$AvgPitStopTime[verstappen_data$Season == 2022]
verstappen_2019 <- verstappen_data$AvgPitStopTime[verstappen_data$Season == 2019]

t.test(verstappen_2022, verstappen_2019, paired = TRUE)

"""# Сравнение признаков с неравными дисперсиями"""

# "McLaren", "Force India"
subdata <- clean[clean$Constructor %in% c("McLaren", "Force India"), ]
subdata$Constructor <- droplevels (factor(subdata$Constructor))

library(car)
leveneTest(AvgPitStopTime ~ Constructor, data = subdata)

t.test(AvgPitStopTime ~ Constructor, data = subdata, var.equal = FALSE)

"""# Определение зависимости числового и категориального бинарного признака"""

clean$MoreThanTwoStops <- ifelse(clean$TotalPitStops > 2, "1", "0")
head(clean, 10)

t.test(AvgPitStopTime ~ MoreThanTwoStops, data = clean)

b <- read.csv('/content/anemia_dataset.csv')
head(b, 5)

cols_to_clean <- c("X.Red.Pixel", "X.Green.pixel", "X.Blue.pixel")


outlier_indices <- c()

for (col in cols_to_clean) {
  Q1 <- quantile(b[[col]], 0.25, na.rm = TRUE)
  Q3 <- quantile(b[[col]], 0.75, na.rm = TRUE)
  IQR <- Q3 - Q1

  lower <- Q1 - 1.5 * IQR
  upper <- Q3 + 1.5 * IQR

  outliers <- which(b[[col]] < lower | b[[col]] > upper)


  outlier_indices <- union(outlier_indices, outliers)
}

data <- b[-outlier_indices, ]

library(nortest)
library(tseries)

cols_to_test <- c("X.Red.Pixel", "X.Green.pixel", "X.Blue.pixel")

for (col in cols_to_test) {
  cat("===== Нормальность для:", col, "=====\n")

  print(shapiro.test(data[[col]]))

  cat("\n--------------------------\n\n")
}

"""Данные в этом датасете распределены нормально

# Непарный t-test
"""

library(car)

data$Anaemic <- as.factor(data$Anaemic)
leveneTest(X.Blue.pixel ~ Anaemic, data = data)

gr1 <- data$X.Blue.pixel[data$Anaemic == "Yes"]
gr2 <- data$X.Blue.pixel[data$Anaemic == "No"]

t.test(gr1, gr2, var.equal = TRUE)

"""# Парный t-test"""

t.test(data$X.Blue.pixel, data$X.Green.pixel, paired = TRUE)

"""# Сравнение признаков с неравными дисперсиями"""

subdata <- data[data$Anaemic %in% c("Yes", "No"), ]
subdata$Anaemic <- droplevels (factor(subdata$Anaemic))

library(car)
leveneTest(Hb ~ Anaemic, data = subdata)

t.test(Hb ~ Anaemic, data = subdata, var.equal = FALSE)

"""# **2. Аnalysis of variance**

---


"""

set.seed(42)
sample_data <- clean[sample(1:nrow(clean), 200), ]

constructors <- unique(sample_data$Constructor)

for (team in constructors) {
  team_data <- sample_data$AvgPitStopTime[sample_data$Constructor == team]

  if (length(team_data) >= 3) {
    cat("Shapiro test for", team, ":\n")
    print(shapiro.test(team_data))
    cat("\n")
  } else {
    cat("Пропущено:", team, "- слишком мало данных (", length(team_data), ")\n\n")
  }
}

library(car)
leveneTest(AvgPitStopTime ~ Constructor, data = sample_data)

model1 <- aov(AvgPitStopTime ~ Constructor, data = sample_data)
summary(model1)

model2 <- aov(AvgPitStopTime ~ Constructor + Season, data = sample_data)
summary(model2)

extract_and_adjust_p <- function(anova_model) {
  anova_summary <- summary(anova_model)
  p_values <- anova_summary[[1]][,"Pr(>F)"]
  effect_names <- rownames(anova_summary[[1]])

  p_df <- data.frame(
    Effect = effect_names,
    p.value = p_values,
    adj.p.value.bonf = p.adjust(p_values, method = "bonferroni"),
    adj.p.value.bh   = p.adjust(p_values, method = "BH")
  )

  return(p_df)
}

adjusted_model1 <- extract_and_adjust_p(model1)
adjusted_model2 <- extract_and_adjust_p(model2)

print("Модель 1 (AvgPitStopTime ~ Constructor) с поправками:")
print(adjusted_model1)

print("Модель 2 (AvgPitStopTime ~ Constructor + Season) с поправками:")
print(adjusted_model2)

"""# **1. Сhi test**

---


"""

# Один признак - Season
Season_counts <- table(clean$Season)
Season_counts

chisq.test(Season_counts)

# Два признака - Constructor и Season
team_season_table <- table(clean$Constructor, clean$Season)
team_season_table

chisq.test(team_season_table, correct = TRUE)

"""# Фишера"""

small_data <- clean[clean$Constructor %in% c("Force India", "McLaren"), ]

small_data$TotalPitStops <- as.numeric(as.character(small_data$TotalPitStops))

small_data$MoreThanTwoStops <- ifelse(small_data$TotalPitStops > 2, 1, 0)

table_small <- table(small_data$Constructor, small_data$MoreThanTwoStops)

print(table_small)

fisher.test(table_small)